export const familyMembers = [
  {
    id: 1,
    name: "Ayah",
    city: "Bandung",
    lat: -6.9175,
    lng: 107.6191,
    color: "bg-amber-300",
    initial: "A",
    distance: "2.1 km",
    eta: "12 menit",
    status: "Online",
  },
  {
    id: 2,
    name: "Ibu",
    city: "Bekasi",
    lat: -6.2383,
    lng: 106.9756,
    color: "bg-sky-300",
    initial: "I",
    distance: "95 km",
    eta: "2 jam",
    status: "Online",
  },
  {
    id: 3,
    name: "Kakak",
    city: "Cikarang",
    lat: -6.2615,
    lng: 107.1528,
    color: "bg-rose-300",
    initial: "K",
    distance: "27 km",
    eta: "35 menit",
    status: "Online",
  },
  {
    id: 4,
    name: "Adik",
    city: "Kuningan",
    lat: -6.9768,
    lng: 108.4835,
    color: "bg-violet-300",
    initial: "D",
    distance: "120 km",
    eta: "2 jam 40 menit",
    status: "Online",
  },
  {
    id: 5,
    name: "Paman",
    city: "Riau",
    lat: 0.5071,
    lng: 101.4478,
    color: "bg-emerald-300",
    initial: "P",
    distance: "1.350 km",
    eta: "Pesawat",
    status: "Offline",
  },
];